language: php

php:
  - 5.6
  - 7.0

node_js:
  - "5.0.0"

before_script:
  - travis_retry composer self-update
  - composer install
  - npm set registry https://npm.spatie.be
  - npm set ca null
  - npm install -g npm
  - npm install -g gulp
  - npm install
  - gulp
  - gulp --back

script:
 - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

