language: php

php:
  - 7.0.2

before_script:
  - travis_retry composer self-update
  - composer install
  - nvm install 5
  - npm set registry https://npm.spatie.be
  - npm set ca null
  - npm install -g npm
  - npm install -g gulp
  - npm install
  - gulp
  - gulp --back

script:
 - phpunit --coverage-text --coverage-clover=coverage.clover

